version: '3.8'

services:
  ml-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/mldb
    depends_on:
      - db
    networks:
      - ml-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mldb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge

volumes:
  postgres_data: